Repository Andi-IM/Masjidku, pull requests merged in 2021-05, with the labels that each got.

#2 Development - Create Starter Program
  .idea/gradle.xml
  .idea/vcs.xml
  build.gradle
  src/main/java/org/masjidku/FXMLController.java
  src/main/java/org/masjidku/MainApp.java
  src/main/resources/org/masjidku/main.fxml
  src/main/resources/org/masjidku/styles.css
  src/test/java/SampleTest.java
Labels: enhancement

#5 Design Process
  .idea/vcs.xml
  build.gradle
  src/main/java/Main.java
  src/main/java/org/masjidku/FXMLController.java
  src/main/java/org/masjidku/MainApp.java
  src/main/java/org/masjidku/controller/AboutController.java
  src/main/java/org/masjidku/controller/HomeController.java
  src/main/java/org/masjidku/controller/LoginController.java
  src/main/java/org/masjidku/controller/RootLayoutController.java
  src/main/java/org/masjidku/util/DatabaseConnection.java
  src/main/java/org/masjidku/util/DateUtil.java
  src/main/java/org/masjidku/util/LocalDateAdapter.java
  src/main/java/org/masjidku/util/ReportUtil.java
  src/main/resources/org/masjidku/about.fxml
  src/main/resources/org/masjidku/fontstyles.css
  src/main/resources/org/masjidku/home.fxml
  src/main/resources/org/masjidku/icon/app_icon.png
  src/main/resources/org/masjidku/icon/favicon.png
  src/main/resources/org/masjidku/login.fxml
  src/main/resources/org/masjidku/main.fxml
  src/main/resources/org/masjidku/report/Report.jrxml
  src/main/resources/org/masjidku/root_layout.fxml
  src/main/resources/org/masjidku/styles.css
  src/test/java/org/masjidku/DateTest.java
  src/test/java/org/masjidku/SampleTest.java
Labels: enhancement

#6 Design Development
  .idea/dataSources.xml
  .idea/libraries-with-intellij-classes.xml
  .idea/sqldialects.xml
  build.gradle
  src/main/java/org/masjidku/admin/HomeController.java
  src/main/java/org/masjidku/model/User.java
  src/main/java/org/masjidku/model/UserDao.java
  src/main/java/org/masjidku/util/DatabaseConnection.java
  src/main/java/org/masjidku/util/UserSession.java
  src/main/resources/org/masjidku/about.fxml
  src/main/resources/org/masjidku/admin/fontstyles.css
  src/main/resources/org/masjidku/admin/home.fxml
  src/main/resources/org/masjidku/admin/styles.css
  src/main/resources/org/masjidku/db/masjidku.sql
  src/main/resources/org/masjidku/principal/fontstyles.css
  src/main/resources/org/masjidku/principal/styles.css
  src/main/resources/org/masjidku/secretary/fontstyles.css
  src/main/resources/org/masjidku/secretary/styles.css
Labels: enhancement

#7 Simplify Project structure,
  src/main/java/org/masjidku/controller/LoginController.java
  src/main/java/org/masjidku/model/UserDao.java
  src/main/resources/org/masjidku/about.fxml
  src/main/resources/org/masjidku/admin/home.fxml
  src/main/resources/org/masjidku/admin/styles.css
  src/main/resources/org/masjidku/fontstyles.css
  src/main/resources/org/masjidku/home.fxml
  src/main/resources/org/masjidku/login.fxml
  src/main/resources/org/masjidku/principal/fontstyles.css
  src/main/resources/org/masjidku/principal/styles.css
  src/main/resources/org/masjidku/root_layout.fxml
  src/main/resources/org/masjidku/secretary/fontstyles.css
  src/main/resources/org/masjidku/secretary/styles.css
  src/main/resources/org/masjidku/styles/fontstyles.css
Labels: enhancement

#9 Update Login Workflow,
  .github/workflows/cicd-test.yml
  build.gradle
  src/main/java/org/masjidku/MainApp.java
  src/main/java/org/masjidku/admin/AdminHome.java
  src/main/java/org/masjidku/admin/AdminRoot.java
  src/main/java/org/masjidku/admin/HomeController.java
  src/main/java/org/masjidku/admin/UserForm.java
  src/main/java/org/masjidku/admin/UserLists.java
  src/main/java/org/masjidku/controller/LoginController.java
  src/main/java/org/masjidku/controller/RootLayoutController.java
  src/main/java/org/masjidku/model/Jabatan.java
  src/main/java/org/masjidku/model/ProfilUserDao.java
  src/main/java/org/masjidku/model/User.java
  src/main/java/org/masjidku/model/UserDao.java
  src/main/java/org/masjidku/util/DatabaseConnection.java
  src/main/resources/org/masjidku/admin/admin_root.fxml
  src/main/resources/org/masjidku/admin/home.fxml
  src/main/resources/org/masjidku/admin/user_form.fxml
  src/main/resources/org/masjidku/admin/user_lists.fxml
  src/main/resources/org/masjidku/db/masjidku.sql
  src/main/resources/org/masjidku/home.fxml
  src/main/resources/org/masjidku/home_root.fxml
  src/main/resources/org/masjidku/icon/logout.png
  src/main/resources/org/masjidku/login.fxml
  src/main/resources/org/masjidku/root_layout.fxml
  src/main/resources/org/masjidku/styles.css
  src/main/resources/org/masjidku/styles/admin.css
  src/main/resources/org/masjidku/styles/styles.css
  src/test/java/org/masjidku/DbTest.java
Labels: bug, enhancement

#10 Admin Log Developing
  .idea/inspectionProfiles/Project_Default.xml
  build.gradle
  src/main/java/org/masjidku/MainApp.java
  src/main/java/org/masjidku/admin/AdminHome.java
  src/main/java/org/masjidku/admin/AdminRoot.java
  src/main/java/org/masjidku/admin/UserForm.java
  src/main/java/org/masjidku/admin/UserLists.java
  src/main/java/org/masjidku/controller/AboutController.java
  src/main/java/org/masjidku/controller/LoginController.java
  src/main/java/org/masjidku/model/ProfilUserDao.java
  src/main/java/org/masjidku/model/User.java
  src/main/java/org/masjidku/model/UserDao.java
  src/main/java/org/masjidku/util/LocalDateAdapter.java
  src/main/java/org/masjidku/util/ReportUtil.java
  src/main/java/org/masjidku/util/UserSession.java
  src/main/resources/org/masjidku/about.fxml
  src/main/resources/org/masjidku/admin/admin_home.fxml
  src/main/resources/org/masjidku/admin/admin_root.fxml
  src/main/resources/org/masjidku/admin/home.fxml
  src/main/resources/org/masjidku/admin/user_form.fxml
  src/main/resources/org/masjidku/admin/user_lists.fxml
  src/main/resources/org/masjidku/home.fxml
  src/main/resources/org/masjidku/home_root.fxml
  src/main/resources/org/masjidku/login.fxml
  src/main/resources/org/masjidku/styles/styles.css
  src/test/java/org/masjidku/DateTest.java
Labels: enhancement

#11 Give Task to other
  src/main/java/org/masjidku/accountant/AccountantHome.java
  src/main/java/org/masjidku/accountant/AccountantRoot.java
  src/main/java/org/masjidku/admin/UserLists.java
  src/main/java/org/masjidku/controller/LoginController.java
  src/main/java/org/masjidku/model/User.java
  src/main/java/org/masjidku/model/UserDao.java
  src/main/java/org/masjidku/principal/PrincipalHome.java
  src/main/java/org/masjidku/principal/PrincipalRoot.java
  src/main/java/org/masjidku/secretary/SecretaryHome.java
  src/main/java/org/masjidku/secretary/SecretaryRoot.java
  src/main/resources/org/masjidku/accountant/accountant_home.fxml
  src/main/resources/org/masjidku/accountant/accountant_root.fxml
  src/main/resources/org/masjidku/admin/user_lists.fxml
  src/main/resources/org/masjidku/principal/principal_home.fxml
  src/main/resources/org/masjidku/principal/principal_root.fxml
  src/main/resources/org/masjidku/secretary/secretary_home.fxml
  src/main/resources/org/masjidku/secretary/secretary_root.fxml
Labels: help wanted

#12 Development
  src/main/java/org/masjidku/MainApp.java
  src/main/java/org/masjidku/admin/UserForm.java
  src/main/java/org/masjidku/admin/UserLists.java
  src/main/java/org/masjidku/model/User.java
  src/main/java/org/masjidku/model/UserDao.java
  src/main/resources/org/masjidku/about.fxml
  src/main/resources/org/masjidku/admin/admin_home.fxml
  src/main/resources/org/masjidku/admin/admin_root.fxml
  src/main/resources/org/masjidku/admin/user_form.fxml
  src/main/resources/org/masjidku/admin/user_lists.fxml
  src/main/resources/org/masjidku/home.fxml
  src/main/resources/org/masjidku/home_root.fxml
  src/main/resources/org/masjidku/icon/Tasks.png
  src/main/resources/org/masjidku/icon/trash.png
  src/main/resources/org/masjidku/login.fxml
  src/main/resources/org/masjidku/styles/styles.css
  src/test/java/org/masjidku/DbTest.java
  src/test/java/org/masjidku/SampleTest.java
Labels: enhancement

#16 Handle secretary view
  src/main/java/org/masjidku/secretary/SecretaryHome.java
  src/main/java/org/masjidku/secretary/SecretaryKegiatanForm.java
  src/main/resources/org/masjidku/icon/kelola_kegiatan.png
  src/main/resources/org/masjidku/secretary/secretary_home.fxml
  src/main/resources/org/masjidku/secretary/secretary_kegiatan.fxml
  src/main/resources/org/masjidku/secretary/secretary_kegiatan_form.fxml
  src/main/resources/org/masjidku/secretary/secretary_root.fxml
Labels: enhancement

#17 Update secretary_root.fxml
  src/main/resources/org/masjidku/secretary/secretary_root.fxml
Labels: enhancement
